version: "3"

services:
  app:
    image: python:3.12
    container_name: create_parent_container
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "pip install -r requirements.txt && /bin/bash"
    tty: true
    stdin_open: true
